# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: chtual <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/12/04 17:31:34 by chtual            #+#    #+#              #
#    Updated: 2017/12/04 17:45:48 by chtual           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
NAME = ft_display_file
CC = gcc -Wall -Wextra -Werror
SRC = ft_display_file.c
OBJ = ft_display_file.o

all :
	$(CC) -o $(NAME) $(SRC)

clean :
	rm -rf $(OBJ)

fclean : clean
	rm -rf $(NAME)

re : fclean all
